camunda.bpm:
  admin-user:
    id: admin
    password: admin
    firstName: Admin
  filter:
    create: All tasks
    
spring:
  datasource:
    url: jdbc:h2:./camunda-h2-dbs/process-engine;DB_CLOSE_ON_EXIT=false;AUTO_SERVER=TRUE
    username: sa
    password: sa
broker:
  url: tcp://localhost:61616?jms.redeliveryPolicy.maximumRedeliveries=1
  user: admin
  password: admin

server:
  port: 8081
